/**
 * Location constants
 * Country and city mappings for forms and filters
 */

/**
 * Country to cities mapping
 * Used in forms and talent matching filters
 */
export const COUNTRY_CITY = {
  Pakistan: [
    "Karachi",
    "Lahore",
    "Islamabad",
    "Rawalpindi",
    "Peshawar",
    "Quetta",
    "Faisalabad",
    "Multan",
    "Sialkot",
    "Gujranwala",
    "Hyderabad",
  ],
  USA: [
    "New York",
    "San Francisco",
    "Los Angeles",
    "Chicago",
    "Austin",
    "Seattle",
    "Boston",
    "Denver",
    "Miami",
    "Houston",
    "Philadelphia",
  ],
  India: [
    "Mumbai",
    "Delhi",
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Pune",
    "Kolkata",
    "Ahmedabad",
    "Jaipur",
    "Lucknow",
  ],
  UK: [
    "London",
    "Manchester",
    "Birmingham",
    "Leeds",
    "Glasgow",
    "Liverpool",
    "Bristol",
    "Sheffield",
  ],
  Canada: [
    "Toronto",
    "Vancouver",
    "Montreal",
    "Calgary",
    "Ottawa",
    "Edmonton",
    "Winnipeg",
  ],
  Australia: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Canberra",
  ],
  France: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes"],
  Germany: [
    "Berlin",
    "Munich",
    "Frankfurt",
    "Hamburg",
    "Cologne",
    "Stuttgart",
  ],
  Spain: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Zaragoza",
    "Malaga",
  ],
  Italy: ["Rome", "Milan", "Naples", "Turin", "Bologna", "Florence"],
  Netherlands: [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
  ],
  Brazil: [
    "Sao Paulo",
    "Rio de Janeiro",
    "Brasilia",
    "Salvador",
    "Fortaleza",
  ],
  Mexico: [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Tijuana",
  ],
  Argentina: [
    "Buenos Aires",
    "Cordoba",
    "Rosario",
    "Mendoza",
    "La Plata",
  ],
  SouthAfrica: [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
  ],
  Nigeria: ["Lagos", "Abuja", "Ibadan", "Kano", "Port Harcourt"],
  Japan: ["Tokyo", "Osaka", "Yokohama", "Nagoya", "Sapporo"],
  China: ["Beijing", "Shanghai", "Shenzhen", "Guangzhou", "Chengdu"],
  SouthKorea: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
  Indonesia: [
    "Jakarta",
    "Surabaya",
    "Bandung",
    "Medan",
    "Semarang",
  ],
  Malaysia: [
    "Kuala Lumpur",
    "George Town",
    "Johor Bahru",
    "Ipoh",
    "Kota Kinabalu",
  ],
  Thailand: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Hat Yai"],
  Vietnam: [
    "Hanoi",
    "Ho Chi Minh City",
    "Da Nang",
    "Can Tho",
    "Nha Trang",
  ],
  UAE: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Al Ain"],
  SaudiArabia: ["Riyadh", "Jeddah", "Dammam", "Medina", "Mecca"],
  Turkey: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya"],
  Egypt: [
    "Cairo",
    "Alexandria",
    "Giza",
    "Shubra El-Kheima",
    "Port Said",
  ],
  Poland: ["Warsaw", "Krakow", "Lodz", "Wroclaw", "Poznan"],
  Ireland: ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  Chile: [
    "Santiago",
    "Valparaiso",
    "Concepcion",
    "Antofagasta",
    "Temuco",
  ],
  Colombia: [
    "Bogota",
    "Medellin",
    "Cali",
    "Barranquilla",
    "Cartagena",
  ],
  Other: ["Other City"],
};




